development:
  GOOGLE_GEOCODER: "AIzaSyC2nMgX7whyi_atOWvRuo4aK0NgOEey0nE"
  SMTP_USERNAME: "AKIAT4GORE7OYF64PTGQ"
  SMTP_PASSWORD: "BLPI+E+2CpxYObxIuxzmUtWeIzoa5i+z8GH9g3sc5OBg"
  QUICKBOOKS_AUTH_ENDPOINT: "https://appcenter.intuit.com/connect/oauth2"
  QUICKBOOKS_CLIENT_ID: "ABGbBlBPYA9PjBqmK6QmvD2N7Fz7wedJD0lvX4xvibXDzFaMAm"
  QUICKBOOKS_REDIRECT_URI: "https://00b7-24-202-102-107.ngrok.io/quickbooks/callback"
  QUICKBOOKS_SECRET: "Ss5pbFXXxTc9haKOV2jFPuU1VBTs9nE6ilSmKq1b"
  QUICKBOOKS_TOKEN_ENDPOINT: "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer"
  INTERNAL_NOTIFICATION_EMAIL: "parfaitmenage@fungo.ca"
  AUTHORIZED_IPS: "127.0.0.1, 172.20.0.1, 192.168.0.1"
  PAYSAFE_ACCOUNT_NUMBER: "1001605970"
  PAYSAFE_CLIENT_ID: "test_fungo"
  PAYSAFE_CLIENT_SECRET: "B-qa2-0-5dcb21e0-0-302c02146960e00f9a01981e736354e328b9cb44e263cd3e021460d9f595325320bded26f1ee9124f1ff7effe06c"
  PAYSAFE_SINGLE_USE_TOKEN_USER: "OT-398920"
  PAYSAFE_SINGLE_USE_TOKEN_PSW: "B-qa2-0-5dcb2270-0-302c02140cd44a86270489ab7a81468f4197cb91c5476bc20214550498c5ad04b6ff6cfc40c9cf6afbb2a4ad7fb4"
  CRM_URL: "https://crm.parfaitmenage.fungo.ca"
  BLAZER_DATABASE_URL: "mysql2://blazer:fungo2000@ls-166f1de20cc4625ec9022dd992cdfa360091ac88.chnxcw8c76mx.ca-central-1.rds.amazonaws.com:3306/parfaitmenage_app_staging"
test:
  GOOGLE_GEOCODER: "AIzaSyC2nMgX7whyi_atOWvRuo4aK0NgOEey0nE"
  SMTP_USERNAME: "AKIAT4GORE7OYF64PTGQ"
  SMTP_PASSWORD: "BLPI+E+2CpxYObxIuxzmUtWeIzoa5i+z8GH9g3sc5OBg"
  QUICKBOOKS_AUTH_ENDPOINT: "https://appcenter.intuit.com/connect/oauth2"
  QUICKBOOKS_CLIENT_ID: "Q0JJ73qnOznBo9gOMF4XcVni2lSE4TINopVSWtPgYlYiNc42Om"
  QUICKBOOKS_REDIRECT_URI: "http://localhost:3001/quickbooks/callback"
  QUICKBOOKS_SECRET: "cAOxbjc5e5zQvXJyZ5frr6IlImO4IOn0X56F2bRU"
  QUICKBOOKS_TOKEN_ENDPOINT: "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer"
  AUTHORIZED_IPS: "127.0.0.1"
